package com.bacsystem.auth.audit;

public enum AuditAction {
    BOOTSTRAP_TENANT_CREATED,
    USER_CREATED,
    USER_DEACTIVATED,
    USER_PASSWORD_CHANGED,
    ROLE_CREATED,
    ROLE_DELETED,
    ROLE_PERMISSIONS_REPLACED,
    PERMISSION_CATALOG_SYNCED,
    ROLE_ASSIGNED,
    ROLE_REVOKED,
    MFA_ENROLLED,
    MFA_ADMIN_RESET,
    KEY_ROTATION,
    KEY_ROTATION_EMERGENCY,
    RETENTION_JOB_RUN,
    REFRESH_TOKEN_REUSE_DETECTED,
    REFRESH_TOKEN_CLIENT_MISMATCH
}
