import { AiChatMenuContent } from "./app/(dashboard)/applications/ai-chat/components/menu-content";
import { AiContentMenuContent } from "./app/(dashboard)/applications/ai-content/components/menu-content";
import { CalendarMenuContent } from "./app/(dashboard)/applications/calendar/components/menu-content";
import { DriveMenuContent } from "./app/(dashboard)/applications/drive/components/menu-content";
import { MessagesMenuContent } from "./app/(dashboard)/applications/messages/components/menu-content";

import { MenuItem } from "@/types";

export const leftMenuItems: MenuItem[] = [
  {
    id: "dashboards",
    icon: "NiStore",
    label: "menu-dashboards",
    description: "menu-dashboards-description",
    color: "text-primary",
    href: "/dashboards",
    children: [
      {
        id: "default",
        icon: "NiChartPie",
        label: "menu-default",
        href: "/dashboards/default",
        description: "menu-default-description",
      },
      {
        id: "default-titles-inside",
        icon: "NiChartPie",
        label: "menu-default-titles-inside",
        href: "/dashboards/default/default-titles-inside",
        description: "menu-default-description",
        hideInMenu: true,
      },
      {
        id: "analytics",
        icon: "NiPresentation",
        label: "menu-analytics",
        href: "/dashboards/analytics",
        description: "menu-analytics-description",
      },
      {
        id: "analytics-titles-inside",
        icon: "NiPresentation",
        label: "menu-analytics-titles-inside",
        href: "/dashboards/analytics/analytics-titles-inside",
        description: "menu-analytics-description",
        hideInMenu: true,
      },
      {
        id: "visual",
        icon: "NiTextarea",
        label: "menu-visual",
        href: "/dashboards/visual",
        description: "menu-visual-description",
      },
      {
        id: "visual-titles-inside",
        icon: "NiTextarea",
        label: "menu-visual-titles-inside",
        href: "/dashboards/visual/visual-titles-inside",
        description: "menu-visual-description",
        hideInMenu: true,
      },
      {
        id: "commerce",
        icon: "NiBag",
        label: "menu-commerce",
        href: "/dashboards/commerce",
        description: "menu-commerce-description",
      },
      {
        id: "commerce-titles-inside",
        icon: "NiBag",
        label: "menu-commerce-titles-inside",
        href: "/dashboards/commerce/commerce-titles-inside",
        description: "menu-commerce-description",
        hideInMenu: true,
      },
      {
        id: "learning",
        icon: "NiGraduation",
        label: "menu-learning",
        href: "/dashboards/learning",
        description: "menu-learning-description",
      },
      {
        id: "learning-titles-inside",
        icon: "NiGraduation",
        label: "menu-learning-titles-inside",
        href: "/dashboards/learning/learning-titles-inside",
        description: "menu-learning-description",
        hideInMenu: true,
      },
      {
        id: "health",
        icon: "NiHeartRate",
        label: "menu-health",
        href: "/dashboards/health",
        description: "menu-health-description",
      },
      {
        id: "health-titles-inside",
        icon: "NiHeartRate",
        label: "menu-health-titles-inside",
        href: "/dashboards/health/health-titles-inside",
        description: "menu-health-description",
        hideInMenu: true,
      },
      {
        id: "finance",
        icon: "NiWallet",
        label: "menu-finance",
        href: "/dashboards/finance",
        description: "menu-finance-description",
      },
      {
        id: "finance-titles-inside",
        icon: "NiWallet",
        label: "menu-finance-titles-inside",
        href: "/dashboards/finance/finance-titles-inside",
        description: "menu-finance-description",
        hideInMenu: true,
      },
      {
        id: "booking",
        icon: "NiSigns",
        label: "menu-booking",
        href: "/dashboards/booking",
        description: "menu-booking-description",
      },
      {
        id: "booking-titles-inside",
        icon: "NiSigns",
        label: "menu-booking-titles-inside",
        href: "/dashboards/booking/booking-titles-inside",
        description: "menu-booking-description",
        hideInMenu: true,
      },
    ],
  },
  {
    id: "applications",
    icon: "NiCells",
    label: "menu-applications",
    description: "menu-applications-description",
    color: "text-primary",
    href: "/applications",
    children: [
      {
        id: "ai-chat",
        icon: "NiAI",
        label: "menu-ai-chat",
        href: "/applications/ai-chat",
        content: <AiChatMenuContent />,
        children: [
          {
            id: "new-chat",
            label: "menu-new-chat",
            href: "/applications/ai-chat/new-chat",
          },
          {
            id: "extensions",
            label: "menu-extensions",
            href: "/applications/ai-chat/extensions",
          },
          {
            id: "extension-detail",
            label: "menu-extension-detail",
            href: "/applications/ai-chat/extension-detail",
          },
          {
            id: "api-access",
            label: "menu-api-access",
            href: "/applications/ai-chat/api-access",
          },
          {
            id: "premium-plans",
            label: "menu-premium-plans",
            href: "/applications/ai-chat/premium-plans",
          },
          {
            id: "settings",
            label: "menu-settings",
            href: "/applications/ai-chat/settings",
          },
          {
            id: "recent-chat",
            label: "menu-recent-chat",
            href: "/applications/ai-chat/recent-chat",
          },
        ],
      },
      {
        id: "ai-content",
        icon: "NiPalette",
        label: "menu-ai-content",
        href: "/applications/ai-content",
        content: <AiContentMenuContent />,
        children: [
          {
            id: "ai-content-home",
            label: "menu-home",
            href: "/applications/ai-content/home",
          },
          {
            id: "ai-image",
            label: "menu-ai-image",
            href: "/applications/ai-content/ai-image",
          },
          {
            id: "ai-models",
            label: "menu-ai-models",
            href: "/applications/ai-content/ai-models",
          },
          {
            id: "ai-models-detail",
            label: "menu-ai-models-detail",
            href: "/applications/ai-content/ai-models/detail",
          },
          {
            id: "ai-upscale",
            label: "menu-ai-upscale",
            href: "/applications/ai-content/ai-upscale",
          },
          {
            id: "ai-video",
            label: "menu-ai-video",
            href: "/applications/ai-content/ai-video",
          },
          {
            id: "api-access",
            label: "menu-api-access",
            href: "/applications/ai-content/api-access",
          },
          {
            id: "faq",
            label: "menu-faq",
            href: "/applications/ai-content/faq",
          },
          {
            id: "learn",
            label: "menu-learn",
            href: "/applications/ai-content/learn",
          },
          {
            id: "library",
            label: "menu-library",
            href: "/applications/ai-content/library",
          },
          {
            id: "premium-plans",
            label: "menu-premium-plans",
            href: "/applications/ai-content/premium-plans",
          },
          {
            id: "settings",
            label: "menu-settings",
            href: "/applications/ai-content/settings",
          },
          {
            id: "uploads",
            label: "menu-uploads",
            href: "/applications/ai-content/uploads",
          },
        ],
      },
      {
        id: "calendar",
        icon: "NiCalendar",
        label: "menu-calendar",
        href: "/applications/calendar",
        content: <CalendarMenuContent />,
        children: [
          {
            id: "calendar-home",
            label: "calendar-home",
            href: "/applications/calendar/home",
          },
          {
            id: "add-event",
            label: "add-event",
            href: "/applications/calendar/add-event",
          },
        ],
      },
      {
        id: "drive",
        icon: "NiFolder",
        label: "menu-drive",
        href: "/applications/drive",
        content: <DriveMenuContent />,
        children: [
          {
            id: "drive-home",
            label: "menu-home",
            href: "/applications/drive/home",
          },
          {
            id: "files",
            label: "menu-files",
            href: "/applications/drive/files",
          },
          {
            id: "favorites",
            label: "menu-favorites",
            href: "/applications/drive/favorites",
          },
          {
            id: "shared",
            label: "menu-shared",
            href: "/applications/drive/shared",
          },
          {
            id: "spam",
            label: "menu-spam",
            href: "/applications/drive/spam",
          },
          {
            id: "trash",
            label: "menu-trash",
            href: "/applications/drive/trash",
          },
          {
            id: "label",
            label: "menu-label",
            href: "/applications/drive/label",
          },
          {
            id: "folder",
            label: "menu-folder",
            href: "/applications/drive/folder",
          },
          {
            id: "premium-plans",
            label: "menu-premium-plans",
            href: "/applications/drive/premium-plans",
          },
          {
            id: "workspaces",
            label: "menu-workspaces",
            href: "/applications/drive/workspaces",
          },
          {
            id: "organizations",
            label: "menu-organizations",
            href: "/applications/drive/organizations",
          },
          {
            id: "settings",
            label: "menu-settings",
            href: "/applications/drive/settings",
          },
        ],
      },
      {
        id: "messages",
        icon: "NiMessages",
        label: "menu-messages",
        href: "/applications/messages",
        content: <MessagesMenuContent />,
        children: [
          {
            id: "messages-home",
            label: "menu-home",
            href: "/applications/messages/home",
          },
          {
            id: "messages-chat",
            label: "menu-chat",
            href: "/applications/messages/chat",
          },
          {
            id: "messages-chat-new",
            label: "menu-chat",
            href: "/applications/messages/chat-new",
          },
          {
            id: "messages-call",
            label: "menu-call",
            href: "/applications/messages/call",
          },
        ],
      },
    ],
  },
  {
    id: "ui",
    icon: "NiCatalog",
    label: "menu-ui",
    description: "menu-ui-description",
    color: "text-primary",
    href: "/ui",
    children: [
      {
        id: "inputs",
        icon: "NiInput",
        label: "menu-inputs",
        href: "/ui/inputs",
        description: "menu-inputs-description",
        children: [
          {
            id: "autocomplete",
            label: "menu-autocomplete",
            href: "/ui/inputs/autocomplete",
            description: "menu-autocomplete-description",
            listIcon: "NiSelect",
          },
          {
            id: "button",
            label: "menu-button",
            href: "/ui/inputs/button",
            description: "menu-button-description",
            listIcon: "NiButton",
          },
          {
            id: "button-group",
            label: "menu-button-group",
            href: "/ui/inputs/button-group",
            description: "menu-button-group-description",
            listIcon: "NiButtonGroup",
          },
          {
            id: "checkbox",
            label: "menu-checkbox",
            href: "/ui/inputs/checkbox",
            description: "menu-checkbox-description",
            listIcon: "NiListCheck",
          },
          {
            id: "fab",
            label: "menu-floating-action-button",
            href: "/ui/inputs/floating-action-button",
            description: "menu-floating-action-button-description",
            listIcon: "NiButtonLarge",
          },
          {
            id: "number-field",
            label: "menu-number-field",
            href: "/ui/inputs/number-field",
            description: "menu-number-field-description",
            listIcon: "NiDocumentNumber",
          },
          {
            id: "radio-group",
            label: "menu-radio-group",
            href: "/ui/inputs/radio-group",
            description: "menu-radio-group-description",
            listIcon: "NiList",
          },
          {
            id: "rating",
            label: "menu-rating",
            href: "/ui/inputs/rating",
            description: "menu-rating-description",
            listIcon: "NiStars",
          },
          {
            id: "select",
            label: "menu-select",
            href: "/ui/inputs/select",
            description: "menu-select-description",
            listIcon: "NiSelect",
          },
          {
            id: "slider",
            label: "menu-slider",
            href: "/ui/inputs/slider",
            description: "menu-slider-description",
            listIcon: "NiSlider",
          },
          {
            id: "switch",
            label: "menu-switch",
            href: "/ui/inputs/switch",
            description: "menu-switch-description",
            listIcon: "NiSwitch",
          },
          {
            id: "text-field",
            label: "menu-text-field",
            href: "/ui/inputs/text-field",
            description: "menu-text-field-description",
            listIcon: "NiInput",
          },
          {
            id: "toggle-button",
            label: "menu-toggle-button",
            href: "/ui/inputs/toggle-button",
            description: "menu-toggle-button-description",
            listIcon: "NiCheckSquare",
          },
        ],
      },
      {
        id: "data-display",
        icon: "NiSign",
        label: "menu-data-display",
        href: "/ui/data-display",
        description: "menu-data-display-description",
        children: [
          {
            id: "avatar",
            label: "menu-avatar",
            href: "/ui/data-display/avatar",
            description: "menu-avatar-description",
            listIcon: "NiUser",
          },
          {
            id: "badge",
            label: "menu-badge",
            href: "/ui/data-display/badge",
            description: "menu-badge-description",
            listIcon: "NiBadge",
          },
          {
            id: "chip",
            label: "menu-chip",
            href: "/ui/data-display/chip",
            description: "menu-chip-description",
            listIcon: "NiButton",
          },
          {
            id: "divider",
            label: "menu-divider",
            href: "/ui/data-display/divider",
            description: "menu-divider-description",
            listIcon: "NiLayout",
          },
          {
            id: "icons",
            label: "menu-icon",
            href: "/ui/data-display/icons",
            description: "menu-icon-description",
            listIcon: "NiStar",
          },
          {
            id: "nexture-icons",
            label: "menu-nexture-icons",
            href: "/ui/data-display/nexture-icons",
            description: "menu-nexture-icons-description",
            listIcon: "NiStars",
          },
          {
            id: "list",
            label: "menu-list",
            href: "/ui/data-display/list",
            description: "menu-list-description",
            listIcon: "NiList",
          },
          {
            id: "table",
            label: "menu-table",
            href: "/ui/data-display/table",
            description: "menu-table-description",
            listIcon: "NiMasonary",
          },
          {
            id: "tooltip",
            label: "menu-tooltip",
            href: "/ui/data-display/tooltip",
            description: "menu-tooltip-description",
            listIcon: "NiMessageDots",
          },
          {
            id: "typography",
            label: "menu-typography",
            href: "/ui/data-display/typography",
            description: "menu-typography-description",
            listIcon: "NiTextBold",
          },
        ],
      },
      {
        id: "feedback",
        icon: "NiMessageFilled",
        label: "menu-feedback",
        href: "/ui/feedback",
        description: "menu-feedback-description",
        children: [
          {
            id: "alert",
            label: "menu-alert",
            href: "/ui/feedback/alert",
            description: "menu-alert-description",
            listIcon: "NiMessageCross",
          },
          {
            id: "backdrop",
            label: "menu-backdrop",
            href: "/ui/feedback/backdrop",
            description: "menu-backdrop-description",
            listIcon: "NiDuplicate",
          },
          {
            id: "dialog",
            label: "menu-dialog",
            href: "/ui/feedback/dialog",
            description: "menu-dialog-description",
            listIcon: "NiButtonLarge",
          },
          {
            id: "progress",
            label: "menu-progress",
            href: "/ui/feedback/progress",
            description: "menu-progress-description",
            listIcon: "NiProgress",
          },
          {
            id: "skeleton",
            label: "menu-skeleton",
            href: "/ui/feedback/skeleton",
            description: "menu-skeleton-description",
            listIcon: "NiRows",
          },
          {
            id: "snackbar",
            label: "menu-snackbar",
            href: "/ui/feedback/snackbar",
            description: "menu-snackbar-description",
            listIcon: "NiMessages",
          },
        ],
      },
      {
        id: "surfaces",
        icon: "NiCells",
        label: "menu-surfaces",
        href: "/ui/surfaces",
        description: "menu-surfaces-description",
        children: [
          {
            id: "accordion",
            label: "menu-accordion",
            href: "/ui/surfaces/accordion",
            description: "menu-accordion-description",
            listIcon: "NiListChevronDown",
          },
          {
            id: "card",
            label: "menu-card",
            href: "/ui/surfaces/card",
            description: "menu-card-description",
            listIcon: "NiCreditCard",
          },
          {
            id: "paper",
            label: "menu-paper",
            href: "/ui/surfaces/paper",
            description: "menu-paper-description",
            listIcon: "NiMoney",
          },
        ],
      },
      {
        id: "navigation",
        icon: "NiPath",
        label: "menu-navigation",
        href: "/ui/navigation",
        description: "menu-navigation-description",
        children: [
          {
            id: "bottom-navigation",
            label: "menu-bottom-navigation",
            href: "/ui/navigation/bottom-navigation",
            description: "menu-bottom-navigation-description",
            listIcon: "NiSigns",
          },
          {
            id: "breadcrumbs",
            label: "menu-breadcrumbs",
            href: "/ui/navigation/breadcrumbs",
            description: "menu-breadcrumbs-description",
            listIcon: "NiEllipsisHorizontal",
          },
          {
            id: "drawer",
            label: "menu-drawer",
            href: "/ui/navigation/drawer",
            description: "menu-drawer-description",
            listIcon: "NiMenuRight",
          },
          {
            id: "link",
            label: "menu-link",
            href: "/ui/navigation/link",
            description: "menu-link-description",
            listIcon: "NiLink",
          },
          {
            id: "menu",
            label: "menu-menu",
            href: "/ui/navigation/menu",
            description: "menu-menu-description",
            listIcon: "NiMenu",
          },
          {
            id: "pagination",
            label: "menu-pagination",
            href: "/ui/navigation/pagination",
            description: "menu-pagination-description",
            listIcon: "NiChevronLeftRightSmall",
          },
          {
            id: "speed-dial",
            label: "menu-speed-dial",
            href: "/ui/navigation/speed-dial",
            description: "menu-speed-dial-description",
            listIcon: "NiFlash",
          },
          {
            id: "stepper",
            label: "menu-stepper",
            href: "/ui/navigation/stepper",
            description: "menu-stepper-description",
            listIcon: "NiEndRightSmall",
          },
          {
            id: "tabs",
            label: "menu-tabs",
            href: "/ui/navigation/tabs",
            description: "menu-tabs-description",
            listIcon: "NiCols",
          },
        ],
      },
      {
        id: "layout",
        icon: "NiLayout",
        label: "menu-layout",
        href: "/ui/layout",
        description: "menu-layout-description",
        children: [
          {
            id: "box",
            label: "menu-box",
            href: "/ui/layout/box",
            description: "menu-box-description",
            listIcon: "NiSquircle",
          },
          {
            id: "grid",
            label: "menu-grid",
            href: "/ui/layout/grid",
            description: "menu-grid-description",
            listIcon: "NiLayout",
          },
          {
            id: "stack",
            label: "menu-stack",
            href: "/ui/layout/stack",
            description: "menu-stack-description",
            listIcon: "NiRows",
          },
          {
            id: "image-list",
            label: "menu-image-list",
            href: "/ui/layout/image-list",
            description: "menu-image-list-description",
            listIcon: "NiDocumentImage",
          },
        ],
      },
      {
        id: "utils",
        icon: "NiMagicWand",
        label: "menu-utils",
        href: "/ui/utils",
        description: "menu-utils-description",
        children: [
          {
            id: "click-away-listener",
            label: "menu-click-away-listener",
            href: "/ui/utils/click-away-listener",
            description: "menu-click-away-listener-description",
            listIcon: "NiCursor",
          },
          {
            id: "modal",
            label: "menu-modal",
            href: "/ui/utils/modal",
            description: "menu-modal-description",
            listIcon: "NiDuplicate",
          },
          {
            id: "popover",
            label: "menu-popover",
            href: "/ui/utils/popover",
            description: "menu-popover-description",
            listIcon: "NiMessageDots",
          },
          {
            id: "popper",
            label: "menu-popper",
            href: "/ui/utils/popper",
            description: "menu-popper-description",
            listIcon: "NiMessage",
          },
          {
            id: "portal",
            label: "menu-portal",
            href: "/ui/utils/portal",
            description: "menu-portal-description",
            listIcon: "NiArrowUp",
          },
          {
            id: "textarea-autosize",
            label: "menu-textarea-autosize",
            href: "/ui/utils/textarea-autosize",
            description: "menu-textarea-autosize-description",
            listIcon: "NiTextarea",
          },
          {
            id: "transitions",
            label: "menu-transitions",
            href: "/ui/utils/transitions",
            description: "menu-transitions-description",
            listIcon: "NiArrowLeftRight",
          },
        ],
      },
      {
        id: "lab",
        icon: "NiFlask",
        label: "menu-lab",
        href: "/ui/lab",
        description: "menu-lab",
        children: [
          {
            id: "lab-masonry",
            label: "menu-lab-masonry",
            href: "/ui/lab/masonry",
            description: "menu-lab-masonry",
            listIcon: "NiMasonary",
          },
          {
            id: "lab-timeline",
            label: "menu-lab-timeline",
            href: "/ui/lab/timeline",
            description: "menu-lab-timeline",
            listIcon: "NiTimeline",
          },
        ],
      },
      {
        id: "plugins",
        icon: "NiPuzzle",
        label: "menu-plugins",
        href: "/ui/plugins",
        description: "menu-plugins",
        children: [
          {
            id: "plugins-emoji-picker",
            label: "menu-plugins-emoji-picker",
            href: "/ui/plugins/emoji-picker",
            description: "menu-plugins-emoji-picker-description",
            listIcon: "NiFaceSmile",
          },
          {
            id: "plugins-lightbox",
            label: "menu-plugins-lightbox",
            href: "/ui/plugins/lightbox",
            description: "menu-plugins-lightbox-description",
            listIcon: "NiDuplicate",
          },
          {
            id: "plugins-carousel",
            label: "menu-plugins-carousel",
            href: "/ui/plugins/carousel",
            description: "menu-plugins-carousel-description",
            listIcon: "NiArrowLeftRight",
          },
          {
            id: "plugins-video-player",
            label: "menu-plugins-video-player",
            href: "/ui/plugins/video-player",
            description: "menu-plugins-video-player-description",
            listIcon: "NiPlay",
          },
          {
            id: "plugins-text-editor",
            label: "menu-plugins-text-editor",
            href: "/ui/plugins/text-editor",
            description: "menu-plugins-text-editor-description",
            listIcon: "NiInput",
          },
          {
            id: "plugins-dropzone",
            label: "menu-plugins-dropzone",
            href: "/ui/plugins/dropzone",
            description: "menu-plugins-dropzone-description",
            listIcon: "NiArrowInUp",
          },
          {
            id: "plugins-validation",
            label: "menu-plugins-validation",
            href: "/ui/plugins/validation",
            description: "menu-plugins-validation-description",
            listIcon: "NiCheckSquare",
          },
        ],
      },
    ],
  },
  {
    id: "pages",
    icon: "NiPresentation",
    label: "menu-pages",
    description: "menu-pages-description",
    color: "text-primary",
    href: "/pages",
    children: [
      {
        id: "authorization",
        icon: "NiLock",
        label: "menu-authorization",
        href: "/auth",
        description: "menu-authorization-description",
        children: [
          {
            id: "signin",
            label: "menu-signin",
            href: "/auth/sign-in",
            description: "menu-signin-description",
            isExternalLink: true,
            listIcon: "NiArrowInDown",
          },
          {
            id: "signup",
            label: "menu-signup",
            href: "/auth/sign-up",
            description: "menu-signup-description",
            isExternalLink: true,
            listIcon: "NiArrowInUp",
          },
          {
            id: "password-reset",
            label: "menu-password-reset",
            href: "/auth/password-reset",
            description: "menu-password-reset-description",
            isExternalLink: true,
            listIcon: "NiLock",
          },
          {
            id: "password-sent",
            label: "menu-password-sent",
            href: "/auth/password-sent",
            description: "menu-password-sent-description",
            isExternalLink: true,
            listIcon: "NiSendUpRight",
          },
          {
            id: "password-new",
            label: "menu-password-new",
            href: "/auth/password-new",
            description: "menu-password-new-description",
            isExternalLink: true,
            listIcon: "NiArrowCircleLeft",
          },
          {
            id: "get-verification",
            label: "menu-get-verification",
            href: "/auth/get-verification",
            description: "menu-get-verification-description",
            isExternalLink: true,
            listIcon: "NiShield",
          },
          {
            id: "set-verification",
            label: "menu-set-verification",
            href: "/auth/set-verification",
            description: "menu-set-verification-description",
            isExternalLink: true,
            listIcon: "NiShieldCheck",
          },
        ],
      },
      {
        id: "ecommerce",
        icon: "NiBasket",
        label: "menu-ecommerce",
        href: "/pages/ecommerce",
        description: "menu-ecommerce-description",
        children: [
          {
            id: "products",
            label: "menu-products",
            href: "/pages/ecommerce/products",
            description: "menu-products-description",
            listIcon: "NiCells",
          },
          {
            id: "products-dense",
            label: "menu-products-dense",
            href: "/pages/ecommerce/products-dense",
            description: "menu-products-dense-description",
            listIcon: "NiRows",
          },
          {
            id: "products-cards",
            label: "menu-products-cards",
            href: "/pages/ecommerce/products-cards",
            description: "menu-products-cards-description",
            listIcon: "NiDocumentImage",
          },
          {
            id: "products-filters",
            label: "menu-products-filters",
            href: "/pages/ecommerce/products-filters",
            description: "menu-products-filters-description",
            listIcon: "NiFilter",
          },
          {
            id: "product-detail",
            label: "menu-product-detail",
            href: "/pages/ecommerce/product-detail",
            description: "menu-product-detail-description",
            listIcon: "NiBag",
          },
          {
            id: "orders",
            label: "menu-orders",
            href: "/pages/ecommerce/orders",
            description: "menu-orders-description",
            listIcon: "NiCartPlus",
          },
          {
            id: "order-detail",
            label: "menu-order-detail",
            href: "/pages/ecommerce/order-detail",
            description: "menu-order-detail-description",
            listIcon: "NiCartEmpty",
          },
          {
            id: "invoice",
            label: "menu-invoice",
            href: "/pages/ecommerce/invoice",
            description: "menu-invoice-description",
            listIcon: "NiReceipt",
          },
        ],
      },
      {
        id: "user",
        icon: "NiUser",
        label: "menu-user",
        href: "/pages/user",
        description: "menu-user-description",
        children: [
          {
            id: "user-overview",
            label: "menu-overview",
            href: "/pages/user/overview",
            description: "menu-overview-description",
            listIcon: "NiUser",
          },
          {
            id: "projects",
            label: "menu-projects",
            href: "/pages/user/projects",
            description: "menu-projects-description",
            listIcon: "NiCatalog",
          },
          {
            id: "permissions",
            label: "menu-permissions",
            href: "/pages/user/permissions",
            description: "menu-permissions-description",
            listIcon: "NiLock",
          },
          {
            id: "friends",
            label: "menu-friends",
            href: "/pages/user/friends",
            description: "menu-friends-description",
            listIcon: "NiUsers",
          },
          {
            id: "social",
            label: "menu-social",
            href: "/pages/user/social",
            description: "menu-social-description",
            listIcon: "NiLike",
          },
        ],
      },
      {
        id: "support",
        icon: "NiQuestionHexagon",
        label: "menu-support",
        href: "/pages/support",
        description: "menu-support-description",
        children: [
          {
            id: "support-overview",
            label: "menu-overview",
            href: "/pages/support/overview",
            description: "menu-overview-description",
            listIcon: "NiQuestionHexagon",
          },
          {
            id: "issues",
            label: "menu-issues",
            href: "/pages/support/issues",
            description: "menu-issues-description",
            listIcon: "NiExclamationSquare",
          },
          {
            id: "issue-detail",
            label: "menu-issue-detail",
            href: "/pages/support/issue-detail",
            description: "menu-issue-detail-description",
            listIcon: "NiExclamationHexagon",
          },
          {
            id: "add-issue",
            label: "menu-add-issue",
            href: "/pages/support/add-issue",
            description: "menu-add-issue-description",
            listIcon: "NiPlusSquare",
          },
        ],
      },
      {
        id: "miscellaneous",
        icon: "NiCatalog",
        label: "menu-miscellaneous",
        href: "/pages/miscellaneous",
        description: "menu-miscellaneous-description",
        children: [
          {
            id: "faq",
            label: "menu-faq",
            href: "/pages/miscellaneous/faq",
            description: "menu-faq-description",
            listIcon: "NiQuestionHexagon",
          },
          {
            id: "knowledge-base",
            label: "menu-knowledge-base",
            href: "/pages/miscellaneous/knowledge-base",
            description: "menu-knowledge-base-description",
            listIcon: "NiBookmark",
          },
          {
            id: "article",
            label: "menu-article",
            href: "/pages/miscellaneous/article",
            description: "menu-article-description",
            listIcon: "NiDocumentFull",
          },
          {
            id: "search",
            label: "menu-search",
            href: "/pages/miscellaneous/search",
            description: "menu-search-description",
            listIcon: "NiSearch",
          },
          {
            id: "empty",
            label: "menu-empty",
            href: "/pages/miscellaneous/empty",
            description: "menu-empty-description",
            listIcon: "NiSquircle",
          },
          {
            id: "error",
            label: "menu-error",
            href: "/not-found",
            description: "menu-error-description",
            isExternalLink: true,
            listIcon: "NiExclamationSquare",
          },
          {
            id: "email-templates",
            label: "menu-email-templates",
            href: "/pages/miscellaneous/email-templates",
            description: "menu-email-templates-description",
            listIcon: "NiEmail",
          },
        ],
      },
    ],
  },
  {
    id: "external-link",
    icon: "NiExternal",
    label: "menu-external-link",
    color: "text-primary",
    href: "https://themeforest.net/item/acorn-next/32360322",
    isExternalLink: true,
  },
  {
    id: "multi-level",
    label: "menu-multi-level",
    icon: "NiDirectory",
    color: "text-primary",
    href: "/menu-levels",
    children: [
      { id: "level-two", label: "menu-level-two", icon: "NiStar", href: "/menu-levels/level-two" },
      {
        id: "level-two-subs",
        label: "menu-level-two-subs",
        href: "/menu-levels/level-two-subs",
        icon: "NiStars",
        children: [
          { id: "level-three", label: "menu-level-three", href: "/menu-levels/level-two-subs/level-three" },
          {
            id: "level-three-subs",
            label: "menu-level-three-subs",
            href: "/menu-levels/level-two-subs/level-three-subs",
            children: [
              {
                id: "level-four",
                label: "menu-level-four",
                href: "/menu-levels/level-two-subs/level-three-subs/level-four",
              },
              {
                id: "level-four-subs",
                label: "menu-level-four-subs",
                href: "/menu-levels/level-two-subs/level-three-subs/level-four-subs",
                children: [
                  {
                    id: "level-five",
                    label: "menu-level-five",
                    href: "/menu-levels/level-two-subs/level-three-subs/level-four-subs/level-five",
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
];

export const leftMenuBottomItems: MenuItem[] = [
  {
    id: "docs",
    label: "menu-documentation",
    href: "/docs",
    icon: "NiDocumentCode",
    color: "text-primary",
    children: [
      {
        id: "docs-welcome",
        label: "menu-welcome",
        href: "/docs/welcome",
        hideInMenu: true,
        children: [
          {
            id: "docs-introduction",
            label: "docs-introduction",
            href: "/docs/welcome/introduction",
          },
          {
            id: "docs-faq",
            label: "docs-faq",
            href: "/docs/welcome/faq",
          },
          {
            id: "docs-changelog",
            label: "docs-changelog",
            href: "/docs/welcome/changelog",
          },
        ],
      },
      {
        id: "docs-getting-started",
        label: "docs-getting-started",
        href: "/docs/getting-started",
        hideInMenu: true,
        children: [
          {
            id: "docs-installation",
            label: "docs-installation",
            href: "/docs/getting-started/installation",
          },
          {
            id: "docs-file-structure",
            label: "docs-file-structure",
            href: "/docs/getting-started/file-structure",
          },
          {
            id: "docs-routing-and-menu",
            label: "docs-routing-and-menu",
            href: "/docs/getting-started/routing-and-menu",
          },
          {
            id: "docs-multi-language",
            label: "docs-multi-language",
            href: "/docs/getting-started/multi-language",
          },
        ],
      },
      {
        id: "docs-theme",
        label: "menu-theme",
        href: "/docs/theme",
        hideInMenu: true,
        children: [
          {
            id: "docs-settings",
            label: "docs-settings",
            href: "/docs/theme/settings",
          },
          {
            id: "docs-theme-provider",
            label: "docs-theme-provider",
            href: "/docs/theme/theme-provider",
          },
          {
            id: "docs-styling",
            label: "docs-styling",
            href: "/docs/theme/styling",
          },
        ],
      },
    ],
  },
  { id: "settings", label: "menu-settings", href: "/settings", icon: "NiSettings" },
];
